export const DENTAL_DIAGNOSES = [
  "Viêm tủy không hồi phục",
  "Viêm tủy có hồi phục",
  "Hoại tử tủy",
  "Viêm quanh chóp cấp",
  "Áp xe quanh chóp cấp",
  "Viêm quanh chóp mạn",
  "Áp xe quanh chóp mạn",
  "Viêm lợi",
  "Viêm nha chu",
  "Áp xe nha chu",
  "Viêm lợi hoại tử loét cấp (NUG)",
  "Phì đại lợi do thuốc",
  "Viêm quanh implant",
  "Viêm lợi trùm",
  "Viêm huyệt ổ răng khô",
  "Sót chân răng",
  "Nhiệt miệng",
  "Nấm miệng",
  "Bạch sản niêm mạc",
  "Lichen phẳng",
  "Khô miệng",
  "Viêm tuyến nước bọt",
  "U hạt sinh mủ",
  "Nang chân răng",
  "Răng ngầm",
  "Gãy thân răng",
  "Nứt răng",
  "Lún răng chấn thương",
  "Bán trật khớp răng",
  "Rơi răng khỏi ổ",
  "Sâu răng",
  "Mòn cổ răng",
  "Răng chen chúc",
  "Khớp cắn ngược",
  "Khớp cắn sâu",
  "Khớp cắn hở",
  "Mất răng",
  "Polyp tủy",
  "Đau dây thần kinh V",
  "Gãy xương hàm",
  "Thiếu sản men răng"
];

